version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/blog
    overwrite: yes

permissions:
  - object: /home/ubuntu
    owner: 'ubuntu'
    group: 'ubuntu'

hooks:
  AfterInstall:
    - location: ./after-install.sh
