name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Create .env file
        run: |
          touch .env    
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env

        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      # - name: initial set deploy directory
      #   run: |
      #     mkdir -p deploy/{blog,blog-admin}
      #     mv appspec.yml deploy
      #     mv after-install.sh deploy
      #     mv .env deploy
      #     ls apps/blog-admin

      # - name: blog mv build
      #   run: |
      #     mv blog.dockerfile deploy/blog
      #     mv apps/blog/.next deploy/blog
      #     mv apps/blog/package.json deploy/blog

      # - name: blog-admin mv build
      #   run: |
      #     mv blog-admin.dockerfile deploy/blog-admin
      #     mv apps/blog-admin/dist deploy/blog-admin
      #     mv apps/blog-admin/package.json deploy/blog-admin

      - name: zip build folder
        run: |
          tar cvfz ./deploy.tar.gz ./.

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./deploy.tar.gz s3://chanoo-deploy/chanoo-blog/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name chanoo-deploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name chanoo-blog
          --s3-location bucket=chanoo-deploy,bundleType=tgz,key=chanoo-blog/deploy.tar.gz
